### ISSUE TITLE
DPAI toolbar icon remains on mainmenu

### ISSUE THREAD

**Issue by mwerle** [bfishman/Docking-Port-Alignment-Indicator#1]
A forum user has reported that the DPAI toolbar icon remains visible after returning to the main menu.  Unsure whether this occurs with the stock toolbar or blizzy's toolbar, so some investigation is required.

In general, double-check the startup behaviour for this mod and ensure it only becomes active during flight scenes.

EDIT: User has confirmed they are using the Stock Toolbar.

**Comment by mwerle** [comment]
Confirmed, although not sure why - code limited to Flight Mode only.

Debugger won't attach (stupid corporate firewall so anal it even blocks local traffic) so will take a while to investigate.

**Comment by DomiKamu** [comment]
Hi, the user mwerle mentions in this issue, is me. Having tested 8.6.4.1 debug patch (over 8.6.4), Always show in stock toolbar unchecked (I don't use Blizzy's toolbar), have done few tests, the app icon doesn't appears. As I've replied in forum, perhaps it's the good way. Thanks.

**Comment by mwerle** [comment]
"Always show in stock toolbar" checkbox is unchecked

-> This was the old default.  You need to delete the "config.xml" inside the DPAI folder to see the default settings.
Full path: GameData\NavyFish\Plugins\Docking Port Alignment Indicator\PluginData\DockingPortAlignmentIndicator\config.xml

**Comment by mwerle** [comment]
Root cause of the issue seems to have been that callbacks were being added to GameEvents but not removed. Once the callback was attached several times, the logic restricting the button visibility to FLIGHT mode broke down.

**Comment by mwerle** [comment]
Fixed in v6.8.5.
