### ISSUE TITLE
CKAN Compatibility Error - KSP 1.10.1

### ISSUE THREAD

**Issue by un1c0rn-sec** [bfishman/Docking-Port-Alignment-Indicator#10]
Current version of DPAI is marked as incompatible with KSP 1.10.1 in CKAN.

**Comment by EasyAce** [comment]
Is it incompatible?

**Comment by un1c0rn-sec** [comment]
I'm not entirely sure. I set CKAN to ignore the difference and haven't seen an issue yet.

**Comment by mwerle** [comment]
Nitpick: it's not marked as "incompatible", merely not as "compatible".  This is unfortunately a limitation of SpaceDock which doesn't allow me to mark the mod as compatible with future patch releases of KSP.

Generally speaking, every mod is compatible with all patch releases of KSP, eg, if it says 1.10, then it is compatible with all 1.10.x releases of KSP.  Most mods are also forward-compatible across minor releases, eg a mod for 1.8.x most likely will also work fine on 1.10.x.  There are a handful of mods which don't follow this rule and there are occasional KSP releases which do break things, but those are, thankfully, few and far between these days.

It's very easy to tell CKAN to handle this : Settings -> Compatible KSP Versions.

That said, thank you for the report and apologies for my lack of updating.. it's been a busy year.

**Comment by EasyAce** [comment]
Thank you I understand. Just to confirm. Have tried it with 1.10.1  and not found any bugs yet.

**Comment by un1c0rn-sec** [comment]
@mwerle Thank you for taking the time to look into this, respond, and just be working on this project in general. I had meant to use this to inform you of the issue, not complain that it existed. I apologize if it came off that way.

You're absolutely right about the not marked compatible vs. marked incompatible. It's a small but significant difference. I'll be sure to be more precise if I have issues in the future.

Thank you again for creating this tool. It's very helpful, and we're lucky to have someone donate their time to our fun!

**Comment by mwerle** [comment]
@un1c0rn-sec Sorry, I didn't take your issue as a complaint.  It's just that many people don't realise that many mods are forward-compatbile (and often backwards-compatible)  across many versions of KSP.  So it's sorta my standard response to mention it whenever it comes up.

Also, I'm just the maintainer, @bfishman is the creator :)

But glad you like it!! Makes helping out worthwhile!
